Class project
eerapheal/class-project pull request #1
Opened 2022-06-28 18:59 UTC by eerapheal

School project work.

2022-06-28 20:55 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @eerapheal 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] **Make sure to add a meaningful pull request title and a good description with details of changes you made in the project.**
- [ ] **Make sure you set up [HTML && CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters correctly as is the principal aim of this project** 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 20:55 UTC, tresorsawasawa commented on test.md
> +This file should be ignored by git.
- [ ] Kindly make sure your project has a `.gitignore` file where you ignore the `test.md` file and `node_modules/` directory as required by the project. Once you ignore the `test.md` file, it should not appear on GitHub, but you should have it locally in your root directory, so make sure you remove it from GitHub and ignore it in `.gitignore` file.

2022-06-28 20:55 UTC, tresorsawasawa commented on README.md
> + Hello Microverse.
- [ ] I think it would be better if you replace the **## Project Name** text with the project title itself(e.g.: **Hello Microverse.**) then add a good description of the project which will let users know what is about your project. I suggest you add it where on **line 5** where you deleted the text: "> Description the project...". Make sure you add a description of the project.

2022-06-28 20:55 UTC, tresorsawasawa commented on README.md
> +N/A.
- [ ] Kindly make sure you add an **authors** section and author names with social links as from the [MICROVERSE README template](https://github.com/microverseinc/readme-template) with a good format to make your documentation more professional. e.g.:
```
## Authors

👤 **John Doe **

- GitHub: [@github_usernameme](https://github.com/githubhandle) 
- Twitter: [@twitter_usernameme](https://twitter.com/twitterhandle)
- LinkedIn: [LinkedIn_usernameme](https://linkedin.com/in/linkedinhandle)
```
Notice: In parentheses, you should add links for each profile(GitHub, Twitter, Linkedin) but if no account you can remove it or create a new one.

- [ ] I think it would be better if you complete the **License** section like from the [README template ](https://github.com/microverseinc/readme-template) by adding content you remove from the `MIT.md` file and adding this line in your documentation like from the template: `This project is [MIT](./MIT.md) licensed.` You can also edit the `MIT.md` file content according to your information like your name,...

- [ ] I think it would be better if you complete the content in the issues section and leave there the issues link for someone who wants to contribute to your project with some comments, or suggestions,... to make your document professional. You can use [README as a template](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md) example and complete other sections. This [template will help you to make your documentation professional](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md)

2022-06-29 08:10 UTC, eerapheal commented
I made the required changes and I will make a draft pull request.

2022-06-29 08:10 UTC, closed without merging